### ISSUE TITLE
Ros it's font work no module py hook and we can't install this module too

### ISSUE THREAD

**Issue by furax124** [LopeKinz/project-evoli#7]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

**Comment by LopeKinz** [comment]
I’ll look into that

**Comment by furax124** [comment]
> I’ll look into that

Okay

**Comment by LopeKinz** [comment]
https://pypi.org/project/pyHook/
pyhook can be installed via pip

**Comment by furax124** [comment]
> https://pypi.org/project/pyHook/
> 
> pyhook can be installed via pip

I try but don't work lmao I do pip install pyHook

**Comment by LopeKinz** [comment]
Fork the repo from pyHook and paste it into /src

**Comment by furax124** [comment]
> Fork the repo from pyHook and paste it into /src 

Well okay
